# Plik: .gitlab-ci.yml

image: python:3.11

stages:
  - lint
  - test

before_script:
  - echo "Installing dependencies..."
  # Używamy pliku deweloperskiego do instalacji w CI/CD
  - pip install -r requirements-dev.txt

lint_code:
  stage: lint
  script:
    - echo "Checking code formatting..."
    - black --check .
    - echo "Checking for syntax errors and undefined names..."
    - flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

run_tests:
  stage: test
  script:
    - echo "Running tests with pytest..."
    - pytest
